### PR TITLE
Added Python solution to 206.Reverse Linked List

### PR DESCRIPTION
**Pull request by JoyKrishan**

### CODE REVIEW

**Comment by Tahanima** [comment]
Looks like you've pushed an empty file @JoyKrishan. Please check.

**Comment by JoyKrishan** [comment]
Please check @Tahanima apu

**Comment by Tahanima** [comment]
> Please check @Tahanima apu

Can you please change the folder name from `206_Reverse_Linked_List` to `206_ReverseLinkedList` to match the convention? Also, please delete the file `Algorithms/Medium/7_ReverseInteger/Solution.py`.

**Comment by Tahanima** [comment]
Great work! 🔥🔥🔥

**Pull request merged**
